# Generated by Django 2.1.2 on 2018-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djUsers', '0002_auto_20181111_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
